trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: workspace-ci
      branch: main
      tags:
        - nx-conf-demo-mobile
      trigger:
        branches:
          - main
        tags:
          - nx-conf-demo-mobile

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage_deploy_beta
    displayName: Deploy Beta
    jobs:
      - deployment: deploy_app_store_beta
        displayName: Deploy App Store Beta
        continueOnError: true
        environment: beta.nx-conf-demo-mobile
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - download: ci
                  artifact: nx_conf_demo_mobile
                  displayName: 'Download: nx-conf-demo-mobile'
