trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: workspace-ci
      trigger:
        branches:
          - demo-pipeline-triggers
        tags:
          - nx-conf-demo-mobile

pool:
  vmImage: macos-latest

stages:
  - stage: stage_build
    displayName: Build
    jobs:
      - job: job_build
        displayName: Build iOS
        steps:
          - checkout: self
            displayName: 'Git: checkout'
            fetchDepth: 0

          - script: yarn install
            displayName: 'Yarn: install'

          # - script: npx nx run nx-conf-demo-mobile:archive
          #   displayName: 'Nx: archive'

          - download: ci
            artifact: nx-conf-demo-mobile
            displayName: 'Download: nx-conf-demo-mobile'
