trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: workspace-ci
      branch: demo-pipeline-triggers
      tags:
        - nx-conf-demo-mobile
      trigger:
        branches:
          - main
        tags:
          - nx-conf-demo-mobile

pool:
  vmImage: macos-latest

stages:
  - stage: stage_build
    displayName: Build
    jobs:
      - job: job_build
        displayName: Build iOS
        continueOnError: true
        steps:
          - checkout: none

          - download: ci
            artifact: nx_conf_demo_mobile
            displayName: 'Download: nx-conf-demo-mobile'
