trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: workspace-ci
      trigger:
        branches:
          - demo-pipeline-triggers
        tags:
          - nx-conf-demo-mobile

pool:
  vmImage: macos-latest

stages:
  - stage: stage_build
    displayName: Build
    jobs:
      - job: job_build
        displayName: Build iOS
        steps:
          - checkout: self
            displayName: 'Git: checkout'
            fetchDepth: 0

          - script: yarn install
            displayName: 'Yarn: install'

          # - script: npx nx run nx-conf-demo-mobile:build
          #   displayName: 'Nx: build'
          
          - task: CocoaPods@0
            inputs:
              workingDirectory: 'apps/nx-conf-demo/mobile/ios'
              forceRepoUpdate: true

          - task: Xcode@5
            inputs:
              actions: 'build'
              configuration: 'Release'
              sdk: 'iphoneos'
              xcWorkspacePath: 'apps/nx-conf-demo/mobile/NxConfDemoMobile.xcworkspace'
              scheme: 'NxConfDemoMobile'
              packageApp: false
              useXcpretty: false
