trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: workspace-ci
      branch: demo-pipeline-triggers
      tags:
        - nx-conf-demo-web
      trigger:
        branches:
          - main
        tags:
          - nx-conf-demo-web

pool:
  vmImage: macos-latest

stages:
  - stage: stage_build
    displayName: Deploy
    jobs:
      - job: job_build
        displayName: Publish to Vercel
        continueOnError: true
        steps:
          - checkout: none

          - download: ci
            artifact: nx_conf_demo_web
            displayName: 'Download: nx-conf-demo-web'
