trigger:
  - demo-pipeline-triggers

parameters:
  - name: use_matrix
    displayName: Use a matrix strategy to dynamically create build jobs
    type: boolean
    default: false

pool:
  vmImage: ubuntu-latest

variables:
  BASE_SHA: $(git rev-parse origin/main)

stages:
  - ${{ if eq(parameters.use_matrix, true) }}:
      - stage: stage_build
        displayName: Build
        jobs:
          - job: job_setup
            displayName: Determine Affected
            steps:
              # - checkout: self
              #   displayName: 'Git: checkout'
              #   fetchDepth: 0

              # - script: yarn install
              #   displayName: 'Yarn: install'

              # - script: npx nx print-affected --base=$(BASE_SHA) --select=projects | npx nx workspace-generator ado-matrix
              #   displayName: 'Nx: ado-matrix'
              #   name: generate

              - script: echo "##vso[task.setvariable variable=matrix;isOutput=true]{"nx-conf-demo-mobile":{"image":"macos-latest","sourceRoot":"apps/nx-conf-demo/mobile/ios"},"nx-conf-demo-mobile-e2e":{"image":"ubuntu-latest","sourceRoot":"apps/nx-conf-demo/mobile-e2e/src"},"nx-conf-demo-web":{"image":"ubuntu-latest","sourceRoot":"apps/nx-conf-demo/web"},"nx-conf-demo-web-e2e":{"image":"ubuntu-latest","sourceRoot":"apps/nx-conf-demo/web-e2e/src"},"nx-conf-demo-ui-shared":{"image":"ubuntu-latest","sourceRoot":"libs/nx-conf-demo/ui-shared/src"}}"
                displayName: 'Nx: ado-matrix'
                name: generate

          - job: job_build
            displayName: 'Build:'
            dependsOn: job_setup
            strategy:
              matrix: $[ dependencies.job_setup['generate.matrix'] ]
            pool:
              vmImage: $(image)
            steps:
              - checkout: self
                displayName: 'Git: checkout'
                fetchDepth: 0

  - ${{ if not(eq(parameters.use_matrix, true)) }}:
      - stage: stage_ci
        displayName: Setup
        jobs:
          - job: job_tag
            displayName: Tag Build
            steps:
              - checkout: self
                displayName: 'Git: checkout'
                fetchDepth: 0

              - script: yarn install
                displayName: 'Yarn: install'

              - script: npx nx affected --base=$(BASE_SHA) --target=add-build-tag
                displayName: 'Nx: affected add-build-tag'
