trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  BASE_SHA: $(git rev-parse HEAD~1)

stages:
  - stage: stage_build
    displayName: Build
    jobs:
      - job: job_setup
        displayName: Determine Affected
        steps:
          - checkout: self
            displayName: 'Git: checkout'
            fetchDepth: 0

          - script: yarn install
            displayName: 'Yarn: install'

          - script: npx nx print-affected --base=$(BASE_SHA) --select=projects | npx nx workspace-generator ado-matrix
            displayName: 'Nx: ado-matrix'
            name: generate

      - job: job_build
        displayName: 'Build:'
        dependsOn: job_setup
        continueOnError: 'true'
        strategy:
          matrix: $[ dependencies.job_setup.outputs['generate.matrix'] ]
        pool:
          vmImage: $(image)
        steps:
          - checkout: self
            displayName: 'Git: checkout'
            fetchDepth: 0

          - script: yarn install
            displayName: 'Yarn: install'

          - script: $(buildCommand)
            displayName: 'Nx: build'

          - publish: $(Build.SourcesDirectory)/dist/$(root)
            artifact: $(buildArtifactName)
            displayName: 'Publish: /dist/$(root)'

          - script: $(buildTagCommand)
            displayName: 'Nx: add-build-tag'
