trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage_setup
    displayName: Setup
    jobs:
      - job: job_tag
        displayName: Tag Build
        steps:
          - script: yarn install
            displayName: 'Yarn: install'
