trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage_setup
    jobs:
      - job: job_tag
        displayName: Tag Build
        steps:
          - script: yarn install
            displayName: 'Yarn: install'
          - script: npx nx affected --target=build
            displayName: 'Nx affected: build'
