trigger:
  - demo-pipeline-triggers

pool:
  vmImage: ubuntu-latest

variables:
  BASE_SHA: $(git rev-parse origin/main)

stages:
  - stage: stage_setup
    displayName: Setup
    jobs:
      - job: job_tag
        displayName: Tag Build
        steps:
          - script: yarn install
            displayName: 'Yarn: install'

          - script: npx nx affected --base=$(BASE_SHA) --target=build
            displayName: 'Nx affected: build'
