trigger:
  - demo-pipeline-triggers

pool:
  vmImage: ubuntu-latest

variables:
  BASE_SHA: $(git merge-base $(TARGET_BRANCH) HEAD)

stages:
  - stage: stage_setup
    displayName: Setup
    jobs:
      - job: job_tag
        displayName: Tag Build
        steps:
          - script: yarn install
            displayName: 'Yarn: install'

          - script: npx nx affected --$(BASE_SHA) --target=build
            displayName: 'Nx affected: build'
